// -----------------------------------------------------------------------
// <copyright file="SourceGenerator.cs" company="Altemiq">
// Copyright (c) Altemiq. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

namespace Altemiq.OneOf.CodeGeneration;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

/// <summary>
/// The source generator.
/// </summary>
[Generator]
public partial class SourceGenerator : ISourceGenerator
{
    private const string OneOf = nameof(OneOf);
    private const string TTypeParameter = "T";
    private const string ResultsTypeParameter = TTypeParameter + "Result";
    private const string IndexPropertyName = "Index";
    private const string IndexVariableName = "index";
    private const string ValuePropertyName = "Value";
    private const string ValueVariableName = "value";
    private const string TVariableName = "t";
    private const string LeftVariableName = "left";
    private const string RightVariableName = "right";
    private const string OtherVariableName = "other";

    private const string TrippleSlash = "///";
    private const string Period = ".";
    private const string Space = " ";
    private const string NewLine = @"
";

    /// <inheritdoc/>
    public void Execute(GeneratorExecutionContext context)
    {
        const int Count = 10;

        for (var i = 0; i < Count; i++)
        {
            Add(GenerateOneOfGeneric(i + 1), ref context);
        }

        Add(GenerateOneOf(Count), ref context);

        static void Add((string Name, MemberDeclarationSyntax Declaration) member, ref GeneratorExecutionContext context)
        {
            var sourceText = InNamespace(member.Declaration).NormalizeWhitespace().GetText(System.Text.Encoding.UTF8);
            context.AddSource(member.Name + ".cs", sourceText);
        }

        static BaseNamespaceDeclarationSyntax InNamespace(MemberDeclarationSyntax member)
        {
            return FileScopedNamespaceDeclaration(ParseName("Altemiq"))
                .AddMembers(member)
                .WithLeadingTrivia(TriviaList(Comment("// <autogenerated />")));
        }
    }

    /// <inheritdoc/>
    public void Initialize(GeneratorInitializationContext context)
    {
        // this is required to be implemented
    }

    private static IEnumerable<string> GetTypeParameterNames(int count) => Enumerable.Range(0, count).Select(GetTypeParameterName);

    private static string GetTypeParameterName(int number) => GetName(TTypeParameter, number);

    private static string GetName(string name, int number) => FormattableString.Invariant($"{name}{number}");

    private static IEnumerable<SyntaxNodeOrToken> Join<TNode>(IEnumerable<TNode> source)
        where TNode : SyntaxNode
    {
        var enumerator = source.GetEnumerator();
        if (enumerator.MoveNext())
        {
            yield return enumerator.Current;
        }

        while (enumerator.MoveNext())
        {
            yield return Token(SyntaxKind.CommaToken);
            yield return enumerator.Current;
        }
    }
}