//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altemiq.Properties {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Altemiq.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CannotReturnAsType {
            get {
                return ResourceManager.GetString("CannotReturnAsType", resourceCulture);
            }
        }
        
        internal static string IncorrectInputString {
            get {
                return ResourceManager.GetString("IncorrectInputString", resourceCulture);
            }
        }
        
        internal static string MustBeBetween {
            get {
                return ResourceManager.GetString("MustBeBetween", resourceCulture);
            }
        }
        
        internal static string MustBeNonZero {
            get {
                return ResourceManager.GetString("MustBeNonZero", resourceCulture);
            }
        }
        
        internal static string MustBeNonNegative {
            get {
                return ResourceManager.GetString("MustBeNonNegative", resourceCulture);
            }
        }
        
        internal static string MustBeNonNegativeNonZero {
            get {
                return ResourceManager.GetString("MustBeNonNegativeNonZero", resourceCulture);
            }
        }
        
        internal static string MustBeLessOrEqual {
            get {
                return ResourceManager.GetString("MustBeLessOrEqual", resourceCulture);
            }
        }
        
        internal static string MustBeLess {
            get {
                return ResourceManager.GetString("MustBeLess", resourceCulture);
            }
        }
        
        internal static string MustBeGreaterOrEqual {
            get {
                return ResourceManager.GetString("MustBeGreaterOrEqual", resourceCulture);
            }
        }
        
        internal static string MustBeGreater {
            get {
                return ResourceManager.GetString("MustBeGreater", resourceCulture);
            }
        }
        
        internal static string MustBeEqual {
            get {
                return ResourceManager.GetString("MustBeEqual", resourceCulture);
            }
        }
        
        internal static string MustBeNotEqual {
            get {
                return ResourceManager.GetString("MustBeNotEqual", resourceCulture);
            }
        }
        
        internal static string BitArrayTypeUnsupported {
            get {
                return ResourceManager.GetString("BitArrayTypeUnsupported", resourceCulture);
            }
        }
        
        internal static string InvalidOffLen {
            get {
                return ResourceManager.GetString("InvalidOffLen", resourceCulture);
            }
        }
        
        internal static string RankMultiDimNotSupported {
            get {
                return ResourceManager.GetString("RankMultiDimNotSupported", resourceCulture);
            }
        }
        
        internal static string EmptyOrWhiteSpaceString {
            get {
                return ResourceManager.GetString("EmptyOrWhiteSpaceString", resourceCulture);
            }
        }
        
        internal static string EmptyString {
            get {
                return ResourceManager.GetString("EmptyString", resourceCulture);
            }
        }
        
        internal static string ForwardOnlySeekingAllowed {
            get {
                return ResourceManager.GetString("ForwardOnlySeekingAllowed", resourceCulture);
            }
        }
        
        internal static string ByteArrayTooLarge {
            get {
                return ResourceManager.GetString("ByteArrayTooLarge", resourceCulture);
            }
        }
        
        internal static string CanNotDecodeVarInt {
            get {
                return ResourceManager.GetString("CanNotDecodeVarInt", resourceCulture);
            }
        }
    }
}
